### ISSUE TITLE
Hungry for a more complete and runnable example

### ISSUE THREAD

**Issue by LiuXiaolong19920720** [arvidsson/bt#18]
Thanks for your nice work。I am new to behavior tree and I am learning it, could you please provide a more complete and runnable example? I failed to build the curent one. And I can't get what below codes mean.
`auto targetNearestEnemyNode = std::make_shared<TargetNearestEnemyNode>(blackboard);`

Does this mean that I should write a class named `TargetNearestEnemyNode` like the `WaitNode` in the current example?

**Comment by arvidsson** [comment]
Yes, WaitNode is an example of how a task can be implemented. And all the other example tasks (such as TargetNearestEnemyNode or AttackEnemyNode) would need to be implemented by you in order to get the example to actually run.

I can try to come up with a better and more complete example. Thanks for the input!

**Comment by arvidsson** [comment]
I have updated the example, albeit a bit simple for now. At least it runs :)

**Comment by LiuXiaolong19920720** [comment]
@arvidsson Thank you very much! Finally the examples runs with a little modification.
`sequence.addChild(actionOne);` to `sequence->addChild(actionOne);`    and
`auto tree = BrainTree::TreeBuilder()` to `auto tree = BrainTree::Builder()` cause there is no `TreeBuilder()` to use...
